### ISSUE TITLE
Use of undeclared identifier "SCREENSHOT"

### ISSUE THREAD

**Issue by minuitagency** [BugBattle/ReactNative-SDK#9]
Hi, 

We have five apps that work fine with the BugBattle SDK but for whatever reason on one of our apps (RN 0.61.5) we can't seem to be able to install it, we get the error: 

Use of undeclared identifier "SCREENSHOT", 

![image](https://user-images.githubusercontent.com/38316888/103078348-f4a70500-45d1-11eb-9606-0814e30aa97c.png)

Any idea? 

Thanks,

**Comment by minuitagency** [comment]
Fixed with BugBattle help, very helpful! Needed to do pod repo update and pod update

**Comment by boehlerlukas** [comment]
For future reference:
 
Run
`pod repo update`
`pod update`
within the ios folder of reactnative.

This will update the Bugbattle iOS SDK to the latest version, which also include SCREENSHOT invocation.
